# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eef9ea153c9144c3dd07b190e69e56aeedaa27476e46abb4d66f033947237d1cba90441696d5c834bc59b762b36520f24d1cb3eca3b1452111cf052cca68a50

test:
  secret_key_base: 9031c82dcaf986448e76a83cca375c2942c8a7f39c814387226829db28a087b17c4983ee89d1c6fc47ab025c743eb1aaa24b8ecf7af903e2a6e991de7ead52f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
